package com.webapp.project.modules.student.model;
// Generated Jul 9, 2017 5:31:29 PM by Hibernate Tools 4.3.1.Final


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.webapp.project.framework.model.AppUser;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name="student"
    ,catalog="websystique"
)
public class Student  implements java.io.Serializable {


     private Long studentId;
     private AppUser appUser;
     private String name;
     private Date dob;
     private String gender;
     private String religion;
     private String email;
     private String phone;
     private String address;
     private int classesId;
     private int sectionId;
     private String section;
     private String roll;
     private int library;
     private int hostel;
     private int transport;
     private Date createDate;
     private String totalamount;
     private String paidamount;
     private String photo;
     private Integer parentId;
     private Date year;
     private String username;
     private String password;
     private String usertype;
     private Date modifyDate;
     private Integer createUserId;
     private String createUsername;
     private String createUsertype;
     private int studentactive;

    public Student() {
    }

	
    public Student(String name, Date dob, String gender, int classesId, int sectionId, String section, String roll, int library, int hostel, int transport, Date createDate, String usertype, Date modifyDate, String createUsername, String createUsertype, int studentactive) {
        this.name = name;
        this.dob = dob;
        this.gender = gender;
        this.classesId = classesId;
        this.sectionId = sectionId;
        this.section = section;
        this.roll = roll;
        this.library = library;
        this.hostel = hostel;
        this.transport = transport;
        this.createDate = createDate;
        this.usertype = usertype;
        this.modifyDate = modifyDate;
        this.createUsername = createUsername;
        this.createUsertype = createUsertype;
        this.studentactive = studentactive;
    }
    public Student(AppUser appUser, String name, Date dob, String gender, String religion, String email, String phone, String address, int classesId, int sectionId, String section, String roll, int library, int hostel, int transport, Date createDate, String totalamount, String paidamount, String photo, Integer parentId, Date year, String username, String password, String usertype, Date modifyDate, Integer createUserId, String createUsername, String createUsertype, int studentactive) {
       this.appUser = appUser;
       this.name = name;
       this.dob = dob;
       this.gender = gender;
       this.religion = religion;
       this.email = email;
       this.phone = phone;
       this.address = address;
       this.classesId = classesId;
       this.sectionId = sectionId;
       this.section = section;
       this.roll = roll;
       this.library = library;
       this.hostel = hostel;
       this.transport = transport;
       this.createDate = createDate;
       this.totalamount = totalamount;
       this.paidamount = paidamount;
       this.photo = photo;
       this.parentId = parentId;
       this.year = year;
       this.username = username;
       this.password = password;
       this.usertype = usertype;
       this.modifyDate = modifyDate;
       this.createUserId = createUserId;
       this.createUsername = createUsername;
       this.createUsertype = createUsertype;
       this.studentactive = studentactive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="studentID", unique=true, nullable=false)
    public Long getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="userId")
    public AppUser getAppUser() {
        return this.appUser;
    }
    
    public void setAppUser(AppUser appUser) {
        this.appUser = appUser;
    }

    
    @Column(name="name", nullable=false, length=60)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dob", nullable=false, length=10)
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }

    
    @Column(name="gender", nullable=false, length=10)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="religion", length=25)
    public String getReligion() {
        return this.religion;
    }
    
    public void setReligion(String religion) {
        this.religion = religion;
    }

    
    @Column(name="email", length=40)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="phone")
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="address", length=65535)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="classesID", nullable=false)
    public int getClassesId() {
        return this.classesId;
    }
    
    public void setClassesId(int classesId) {
        this.classesId = classesId;
    }

    
    @Column(name="sectionID", nullable=false)
    public int getSectionId() {
        return this.sectionId;
    }
    
    public void setSectionId(int sectionId) {
        this.sectionId = sectionId;
    }

    
    @Column(name="section", nullable=false, length=60)
    public String getSection() {
        return this.section;
    }
    
    public void setSection(String section) {
        this.section = section;
    }

    
    @Column(name="roll", nullable=false)
    public String getRoll() {
        return this.roll;
    }
    
    public void setRoll(String roll) {
        this.roll = roll;
    }

    
    @Column(name="library", nullable=false)
    public int getLibrary() {
        return this.library;
    }
    
    public void setLibrary(int library) {
        this.library = library;
    }

    
    @Column(name="hostel", nullable=false)
    public int getHostel() {
        return this.hostel;
    }
    
    public void setHostel(int hostel) {
        this.hostel = hostel;
    }

    
    @Column(name="transport", nullable=false)
    public int getTransport() {
        return this.transport;
    }
    
    public void setTransport(int transport) {
        this.transport = transport;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", nullable=false, length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="totalamount", length=128)
    public String getTotalamount() {
        return this.totalamount;
    }
    
    public void setTotalamount(String totalamount) {
        this.totalamount = totalamount;
    }

    
    @Column(name="paidamount", length=128)
    public String getPaidamount() {
        return this.paidamount;
    }
    
    public void setPaidamount(String paidamount) {
        this.paidamount = paidamount;
    }

    
    @Column(name="photo", length=200)
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    
    @Column(name="parentID")
    public Integer getParentId() {
        return this.parentId;
    }
    
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="year", length=0)
    public Date getYear() {
        return this.year;
    }
    
    public void setYear(Date year) {
        this.year = year;
    }

    
    @Column(name="username", length=40)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", length=128)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="usertype", nullable=false, length=20)
    public String getUsertype() {
        return this.usertype;
    }
    
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modify_date", nullable=false, length=19)
    public Date getModifyDate() {
        return this.modifyDate;
    }
    
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    
    @Column(name="create_userID")
    public Integer getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="create_username", nullable=false, length=40)
    public String getCreateUsername() {
        return this.createUsername;
    }
    
    public void setCreateUsername(String createUsername) {
        this.createUsername = createUsername;
    }

    
    @Column(name="create_usertype", nullable=false, length=20)
    public String getCreateUsertype() {
        return this.createUsertype;
    }
    
    public void setCreateUsertype(String createUsertype) {
        this.createUsertype = createUsertype;
    }

    
    @Column(name="studentactive", nullable=false)
    public int getStudentactive() {
        return this.studentactive;
    }
    
    public void setStudentactive(int studentactive) {
        this.studentactive = studentactive;
    }




}


