package com.webapp.project.modules.jobcard.model;
// Generated Jul 9, 2017 1:44:32 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.webapp.project.framework.model.AppUser;
import com.webapp.project.modules.masters.model.CargoType;
import com.webapp.project.modules.masters.model.Consignee;
import com.webapp.project.modules.masters.model.ContainerType;
import com.webapp.project.modules.masters.model.Currency;
import com.webapp.project.modules.masters.model.Customer;
import com.webapp.project.modules.masters.model.Port;

/**
 * Jobcard generated by hbm2java
 */
@Entity
@Table(name = "jobcard", catalog = "websystique")
public class Jobcard implements java.io.Serializable {

	private long jobId;
	private AppUser appUser;
	private CargoType cargoType;
	private Consignee consignee;
	private ContainerType containerType;
	private Currency currency;
	private Customer customer;
	private Port portmasterByPortDischargeId;
	private Port portmasterByPortLoadingId;
	private String jobCode;
	private String jobDetails;
	private String jobNo;
	private String quantityType;
	private Long quantity;
	private Long invoiceValue;
	private Date createDate;
	private Date modifiedDate;
	private Integer createUserId;
	private String createUsername;
	private String createUsertype;

	private String bookingId;
	private Date bookingDate;
	private String bookingParty;
	private Date expectedShipmentDate;
	private String salesPerson;
	private String broker;
	private String shipper;
	private Port portOfOriginId;
	private String shippingLineBookingNo;
	private String FreightTerms;
	private String FinalPlaceOfDelivery;
	private String containerPickupPoint;
	private String emptyContainerLocation;
	private Date containerPickupDate;
	private String cargoReady;
	private Date DocsCutOffDate;
	private Date ACDCutOffDate;
	private Date etd;	
	private String poNumber;
	private String activityName;
	private String mode;
	private String modeOfRealization;
	private String epzIcdCode;
	private String reference;
	private String purposeOfTransfer;
	private String voyNo;
	private String vessel;
	private String viaNo;
	private String consigneeAddress;
	private String buyerAddress;
	private String productHead;
	private String accountPartyName;
	private String address;
	private String grBank;
	private String remark;
	private String category;
	private String rbiWaiverNo;
	private Date rbiWaiverDate;
	private String country;
	private Integer consigneeBuyerSame;
	private String buyer;
	private String buyerCountry;
	private Integer pmvRequired;
	private String service;
	private String organization;
	private String partyAddress;
	private String stateOfOriginOfGoods;
	private String branchNo;
	private String itemCode;
	private String iecCodeNo;
	private String panNo;
	private String exporterClass;
	private String natureOfPayment;
	private String bankName;
	private String periodPfPaymentInDays;
	private String exportContactNo;
	private String drawbackBankAccount;
	private Date date;
	private String terminal;
	
	
	public Jobcard() {
	}

	public Jobcard(long jobId, Date modifiedDate) {
		this.jobId = jobId;
		this.modifiedDate = modifiedDate;
	}

	public Jobcard(long jobId, AppUser appUser, CargoType cargoType, Consignee consignee,
			ContainerType containerType, Currency currency, Customer customer,
			Port portmasterByPortDischargeId, Port portmasterByPortLoadingId, String jobCode,
			String jobDetails, String jobNo, String quantityType, Long quantity, Long invoiceValue, Date createDate,
			Date modifiedDate, Integer createUserId, String createUsername, String createUsertype) {
		this.jobId = jobId;
		this.appUser = appUser;
		this.cargoType = cargoType;
		this.consignee = consignee;
		this.containerType = containerType;
		this.currency = currency;
		this.customer = customer;
		this.portmasterByPortDischargeId = portmasterByPortDischargeId;
		this.portmasterByPortLoadingId = portmasterByPortLoadingId;
		this.jobCode = jobCode;
		this.jobDetails = jobDetails;
		this.jobNo = jobNo;
		this.quantityType = quantityType;
		this.quantity = quantity;
		this.invoiceValue = invoiceValue;
		this.createDate = createDate;
		this.modifiedDate = modifiedDate;
		this.createUserId = createUserId;
		this.createUsername = createUsername;
		this.createUsertype = createUsertype;
	}

	@Id

	@Column(name = "jobId", unique = true, nullable = false)
	public long getJobId() {
		return this.jobId;
	}

	public void setJobId(long jobId) {
		this.jobId = jobId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public AppUser getAppUser() {
		return this.appUser;
	}

	public void setAppUser(AppUser appUser) {
		this.appUser = appUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cargotypeId")
	public CargoType getCargoType() {
		return this.cargoType;
	}

	public void setCargoType(CargoType cargoType) {
		this.cargoType = cargoType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "consigneeId")
	public Consignee getConsignee() {
		return this.consignee;
	}

	public void setConsignee(Consignee consignee) {
		this.consignee = consignee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "containerId")
	public ContainerType getContainerType() {
		return this.containerType;
	}

	public void setContainerType(ContainerType containerType) {
		this.containerType = containerType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "currencyId")
	public Currency getCurrency() {
		return this.currency;
	}

	public void setCurrency(Currency currency) {
		this.currency = currency;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customerId")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "portDischargeId")
	public Port getPortmasterByPortDischargeId() {
		return this.portmasterByPortDischargeId;
	}

	public void setPortmasterByPortDischargeId(Port portmasterByPortDischargeId) {
		this.portmasterByPortDischargeId = portmasterByPortDischargeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "portLoadingId")
	public Port getPortmasterByPortLoadingId() {
		return this.portmasterByPortLoadingId;
	}

	public void setPortmasterByPortLoadingId(Port portmasterByPortLoadingId) {
		this.portmasterByPortLoadingId = portmasterByPortLoadingId;
	}

	@Column(name = "jobCode", length = 65)
	public String getJobCode() {
		return this.jobCode;
	}

	public void setJobCode(String jobCode) {
		this.jobCode = jobCode;
	}

	@Column(name = "jobDetails", length = 100)
	public String getJobDetails() {
		return this.jobDetails;
	}

	public void setJobDetails(String jobDetails) {
		this.jobDetails = jobDetails;
	}

	@Column(name = "jobNo", length = 100)
	public String getJobNo() {
		return this.jobNo;
	}

	public void setJobNo(String jobNo) {
		this.jobNo = jobNo;
	}

	@Column(name = "quantityType", length = 65)
	public String getQuantityType() {
		return this.quantityType;
	}

	public void setQuantityType(String quantityType) {
		this.quantityType = quantityType;
	}

	@Column(name = "quantity", precision = 11, scale = 0)
	public Long getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Long quantity) {
		this.quantity = quantity;
	}

	@Column(name = "invoiceValue", precision = 11, scale = 0)
	public Long getInvoiceValue() {
		return this.invoiceValue;
	}

	public void setInvoiceValue(Long invoiceValue) {
		this.invoiceValue = invoiceValue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date", nullable = false, length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "create_userId")
	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	@Column(name = "create_username", length = 65)
	public String getCreateUsername() {
		return this.createUsername;
	}

	public void setCreateUsername(String createUsername) {
		this.createUsername = createUsername;
	}

	@Column(name = "create_usertype", length = 20)
	public String getCreateUsertype() {
		return this.createUsertype;
	}

	public void setCreateUsertype(String createUsertype) {
		this.createUsertype = createUsertype;
	}

	@Column(name = "bookingId", length = 200)
	public String getBookingId() {
		return bookingId;
	}

	public void setBookingId(String bookingId) {
		this.bookingId = bookingId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bookingDate", length = 19)
	public Date getBookingDate() {
		return bookingDate;
	}

	public void setBookingDate(Date bookingDate) {
		this.bookingDate = bookingDate;
	}

	@Column(name = "bookingParty", length = 200)
	public String getBookingParty() {
		return bookingParty;
	}

	public void setBookingParty(String bookingParty) {
		this.bookingParty = bookingParty;
	}

	@Column(name = "ExpectedShipmentDate", length = 200)
	public Date getExpectedShipmentDate() {
		return expectedShipmentDate;
	}

	public void setExpectedShipmentDate(Date expectedShipmentDate) {
		this.expectedShipmentDate = expectedShipmentDate;
	}

	@Column(name = "salesPerson", length = 200)
	public String getSalesPerson() {
		return salesPerson;
	}

	public void setSalesPerson(String salesPerson) {
		this.salesPerson = salesPerson;
	}

	@Column(name = "broker", length = 200)
	public String getBroker() {
		return broker;
	}

	public void setBroker(String broker) {
		this.broker = broker;
	}

	@Column(name = "shipper", length = 200)
	public String getShipper() {
		return shipper;
	}

	public void setShipper(String shipper) {
		this.shipper = shipper;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PortOfOriginId")
	public Port getPortOfOriginId() {
		return portOfOriginId;
	}

	public void setPortOfOriginId(Port portOfOriginId) {
		this.portOfOriginId = portOfOriginId;
	}

	@Column(name = "ShippingLineBookingNo", length = 200)
	public String getShippingLineBookingNo() {
		return shippingLineBookingNo;
	}

	public void setShippingLineBookingNo(String shippingLineBookingNo) {
		this.shippingLineBookingNo = shippingLineBookingNo;
	}

	@Column(name = "FreightTerms", length = 200)
	public String getFreightTerms() {
		return FreightTerms;
	}

	public void setFreightTerms(String freightTerms) {
		FreightTerms = freightTerms;
	}

	@Column(name = "FinalPlaceOfDelivery", length = 200)
	public String getFinalPlaceOfDelivery() {
		return FinalPlaceOfDelivery;
	}

	public void setFinalPlaceOfDelivery(String finalPlaceOfDelivery) {
		FinalPlaceOfDelivery = finalPlaceOfDelivery;
	}

	@Column(name = "ContainerPickupPoint", length = 200)
	public String getContainerPickupPoint() {
		return containerPickupPoint;
	}

	public void setContainerPickupPoint(String containerPickupPoint) {
		this.containerPickupPoint = containerPickupPoint;
	}
	
	@Column(name = "EmptyContainerLocation", length = 200)
	public String getEmptyContainerLocation() {
		return emptyContainerLocation;
	}

	public void setEmptyContainerLocation(String emptyContainerLocation) {
		this.emptyContainerLocation = emptyContainerLocation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ContainerPickupDate", length = 19)
	public Date getContainerPickupDate() {
		return containerPickupDate;
	}

	public void setContainerPickupDate(Date containerPickupDate) {
		this.containerPickupDate = containerPickupDate;
	}

	@Column(name = "CargoReady", length = 200)
	public String getCargoReady() {
		return cargoReady;
	}

	public void setCargoReady(String cargoReady) {
		this.cargoReady = cargoReady;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DocsCutOffDate", length = 19)
	public Date getDocsCutOffDate() {
		return DocsCutOffDate;
	}

	public void setDocsCutOffDate(Date docsCutOffDate) {
		DocsCutOffDate = docsCutOffDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ACDCutOffDate", length = 19)
	public Date getACDCutOffDate() {
		return ACDCutOffDate;
	}

	public void setACDCutOffDate(Date aCDCutOffDate) {
		ACDCutOffDate = aCDCutOffDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "etd", length = 19)
	public Date getEtd() {
		return etd;
	}

	public void setEtd(Date etd) {
		this.etd = etd;
	}

	@Column(name = "PoNumber", length = 200)
	public String getPoNumber() {
		return poNumber;
	}

	public void setPoNumber(String poNumber) {
		this.poNumber = poNumber;
	}

	@Column(name = "ActivityName", length = 200)
	public String getActivityName() {
		return activityName;
	}

	public void setActivityName(String activityName) {
		this.activityName = activityName;
	}

	@Column(name = "mode", length = 255)
	public String getMode() {
		return mode;
	}

	public void setMode(String mode) {
		this.mode = mode;
	}

	@Column(name = "modeOfRealization", length = 255)
	public String getModeOfRealization() {
		return modeOfRealization;
	}

	public void setModeOfRealization(String modeOfRealization) {
		this.modeOfRealization = modeOfRealization;
	}

	@Column(name = "epzIcdCode", length = 255)
	public String getEpzIcdCode() {
		return epzIcdCode;
	}

	public void setEpzIcdCode(String epzIcdCode) {
		this.epzIcdCode = epzIcdCode;
	}

	@Column(name = "reference", length = 255)
	public String getReference() {
		return reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@Column(name = "purposeOfTransfer", length = 255)
	public String getPurposeOfTransfer() {
		return purposeOfTransfer;
	}

	public void setPurposeOfTransfer(String purposeOfTransfer) {
		this.purposeOfTransfer = purposeOfTransfer;
	}
	
	@Column(name = "voyNo", length = 255)
	public String getVoyNo() {
		return voyNo;
	}

	public void setVoyNo(String voyNo) {
		this.voyNo = voyNo;
	}

	@Column(name = "vessel", length = 255)
	public String getVessel() {
		return vessel;
	}

	public void setVessel(String vessel) {
		this.vessel = vessel;
	}

	@Column(name = "viaNo", length = 255)
	public String getViaNo() {
		return viaNo;
	}

	public void setViaNo(String viaNo) {
		this.viaNo = viaNo;
	}

	@Column(name = "consigneeAddress", length = 255)
	public String getConsigneeAddress() {
		return consigneeAddress;
	}

	public void setConsigneeAddress(String consigneeAddress) {
		this.consigneeAddress = consigneeAddress;
	}

	@Column(name = "buyerAddress", length = 255)
	public String getBuyerAddress() {
		return buyerAddress;
	}

	public void setBuyerAddress(String buyerAddress) {
		this.buyerAddress = buyerAddress;
	}

	@Column(name = "productHead", length = 255)
	public String getProductHead() {
		return productHead;
	}

	public void setProductHead(String productHead) {
		this.productHead = productHead;
	}

	@Column(name = "accountPartyName", length = 255)
	public String getAccountPartyName() {
		return accountPartyName;
	}

	public void setAccountPartyName(String accountPartyName) {
		this.accountPartyName = accountPartyName;
	}

	@Column(name = "organization", length = 255)
	public String getOrganization() {
		return organization;
	}

	public void setOrganization(String organization) {
		organization = organization;
	}

	@Column(name = "address", length = 255)
	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "grBank", length = 255)
	public String getGrBank() {
		return grBank;
	}

	public void setGrBank(String grBank) {
		this.grBank = grBank;
	}

	@Column(name = "remark", length = 255)
	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "category", length = 255)
	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "rbiWaiverNo", length = 255)
	public String getRbiWaiverNo() {
		return rbiWaiverNo;
	}

	public void setRbiWaiverNo(String rbiWaiverNo) {
		this.rbiWaiverNo = rbiWaiverNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rbiWaiverDate", length = 19)
	public Date getRbiWaiverDate() {
		return rbiWaiverDate;
	}

	public void setRbiWaiverDate(Date rbiWaiverDate) {
		this.rbiWaiverDate = rbiWaiverDate;
	}

	@Column(name = "country", length = 255)
	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "consigneeBuyerSame", length = 255)
	public Integer getConsigneeBuyerSame() {
		return consigneeBuyerSame;
	}

	public void setConsigneeBuyerSame(Integer consigneeBuyerSame) {
		this.consigneeBuyerSame = consigneeBuyerSame;
	}

	@Column(name = "buyer", length = 255)
	public String getBuyer() {
		return buyer;
	}

	public void setBuyer(String buyer) {
		this.buyer = buyer;
	}

	@Column(name = "buyerCountry", length = 255)
	public String getBuyerCountry() {
		return buyerCountry;
	}

	public void setBuyerCountry(String buyerCountry) {
		this.buyerCountry = buyerCountry;
	}

	@Column(name = "pmvRequired")
	public Integer getPmvRequired() {
		return pmvRequired;
	}

	public void setPmvRequired(Integer pmvRequired) {
		this.pmvRequired = pmvRequired;
	}

	@Column(name = "service", length = 255)
	public String getService() {
		return service;
	}

	public void setService(String service) {
		this.service = service;
	}

	@Column(name = "partyAddress", length = 255)
	public String getPartyAddress() {
		return partyAddress;
	}

	public void setPartyAddress(String partyAddress) {
		this.partyAddress = partyAddress;
	}

	@Column(name = "stateOfOriginOfGoods", length = 255)
	public String getStateOfOriginOfGoods() {
		return stateOfOriginOfGoods;
	}

	public void setStateOfOriginOfGoods(String stateOfOriginOfGoods) {
		this.stateOfOriginOfGoods = stateOfOriginOfGoods;
	}

	@Column(name = "branchNo", length = 255)
	public String getBranchNo() {
		return branchNo;
	}

	public void setBranchNo(String branchNo) {
		this.branchNo = branchNo;
	}

	@Column(name = "itemCode", length = 255)
	public String getItemCode() {
		return itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	@Column(name = "iecCodeNo", length = 255)
	public String getIecCodeNo() {
		return iecCodeNo;
	}

	public void setIecCodeNo(String iecCodeNo) {
		this.iecCodeNo = iecCodeNo;
	}

	@Column(name = "panNo", length = 255)
	public String getPanNo() {
		return panNo;
	}

	public void setPanNo(String panNo) {
		this.panNo = panNo;
	}

	@Column(name = "exporterClass", length = 255)
	public String getExporterClass() {
		return exporterClass;
	}

	public void setExporterClass(String exporterClass) {
		this.exporterClass = exporterClass;
	}

	@Column(name = "natureOfPayment", length = 255)
	public String getNatureOfPayment() {
		return natureOfPayment;
	}

	public void setNatureOfPayment(String natureOfPayment) {
		this.natureOfPayment = natureOfPayment;
	}

	@Column(name = "bankName", length = 255)
	public String getBankName() {
		return bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "periodPfPaymentInDays", length = 255)
	public String getPeriodPfPaymentInDays() {
		return periodPfPaymentInDays;
	}

	public void setPeriodPfPaymentInDays(String periodPfPaymentInDays) {
		this.periodPfPaymentInDays = periodPfPaymentInDays;
	}

	@Column(name = "exportContactNo", length = 255)
	public String getExportContactNo() {
		return exportContactNo;
	}

	public void setExportContactNo(String exportContactNo) {
		this.exportContactNo = exportContactNo;
	}

	@Column(name = "drawbackBankAccount", length = 255)
	public String getDrawbackBankAccount() {
		return drawbackBankAccount;
	}

	public void setDrawbackBankAccount(String drawbackBankAccount) {
		this.drawbackBankAccount = drawbackBankAccount;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}
	
	public String getTerminal() {
		return terminal;
	}

	public void setTerminal(String terminal) {
		this.terminal = terminal;
	}
	
}
