package com.webapp.project.modules.party.model;
// Generated Jul 9, 2017 1:44:32 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.webapp.project.framework.model.AppUser;
import com.webapp.project.modules.masters.model.City;
import com.webapp.project.modules.masters.model.State;

/**
 * Jobcard generated by hbm2java
 */
@Entity
@Table(name = "party", catalog = "websystique")
public class Party implements java.io.Serializable {

	private long partyId;
	private AppUser appUser;
	private Date createDate;
	private Date modifiedDate;
	private Integer createUserId;
	private String createUsername;
	private String createUsertype;

	private String salesPerson;
	//----------party
	private String accountPartyName;
	private String shortName;
	private String opBalance;
	private String underGroup;
	private String debitCredit;
	private String strDirectory;
	private String bankChequeReport;
	private String rewardDirectory;
	private String textinput;
	private Integer deactivate;
	private String manifestReportName;
	private String binNo;
	private String exporterHouse;
	private Date certificateNo;
	private Date certificateDate;
	private Date validUptoDate;
	private String ifsCode;
	private String stExciseReg;
	private String gstNo;
	private String branchSrNo;
	private String totalBranch;
	private City city;
	private State state;
	private String pinCode;
	private String contactPerson;
	private String phone;
	private String mobile;
	private String email;
	private String commercialTaxRegState;
	private String commercialTaxType;
	private String commercialTaxRegNo;
	private String iecCode;
	private String branchSerialNo;
	private String commissionRate;
	private String division;
	private String range;
	private String name;
	private String branch;
	private String drawBankAccountNo;
	private String bankName;
	private String drawBankAddress;
	private String address;
	private String iecCodeNo;
	private String organization;
	private String panNo;
	private String accountNo;
	private String grBankAdCode;
	private String grBankName;
	private String grBankaddress;
	private String grBankTotalBranch;
	private String iecCodeThirdParty;
	private String branchSrNoThirdParty;
	private String commissionRateThirdParty;
	private String divisionThirdParty;
	private String rangeThirdParty;
	private String nameAddress;
	private String exporterClass;
	private String grBank;
	
	public Party() {
	}

	public Party(long partyId, Date modifiedDate) {
		this.partyId = partyId;
		this.modifiedDate = modifiedDate;
	}

	

	@Id

	@Column(name = "partyId", unique = true, nullable = false)
	public long getPartyId() {
		return this.partyId;
	}

	public void setJobId(long partyId) {
		this.partyId = partyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public AppUser getAppUser() {
		return this.appUser;
	}

	public void setAppUser(AppUser appUser) {
		this.appUser = appUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stateId")
	public State getState() {
		return this.state;
	}

	public void setCargoType(State state) {
		this.state = state;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cityId")
	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createDate", nullable = false, length = 19)
	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifiedDate", nullable = false, length = 19)
	public Date getModifiedDate() {
		return modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "createUserId")
	public Integer getCreateUserId() {
		return createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	@Column(name = "createUsername")
	public String getCreateUsername() {
		return createUsername;
	}

	public void setCreateUsername(String createUsername) {
		this.createUsername = createUsername;
	}

	@Column(name = "createUsertype")
	public String getCreateUsertype() {
		return createUsertype;
	}

	public void setCreateUsertype(String createUsertype) {
		this.createUsertype = createUsertype;
	}

	@Column(name = "salesPerson", length = 255)
	public String getSalesPerson() {
		return salesPerson;
	}

	public void setSalesPerson(String salesPerson) {
		this.salesPerson = salesPerson;
	}

	@Column(name = "accountPartyName", length = 255)
	public String getAccountPartyName() {
		return accountPartyName;
	}

	public void setAccountPartyName(String accountPartyName) {
		this.accountPartyName = accountPartyName;
	}

	@Column(name = "shortName", length = 255)
	public String getShortName() {
		return shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	@Column(name = "opBalance", length = 255)
	public String getOpBalance() {
		return opBalance;
	}

	public void setOpBalance(String opBalance) {
		this.opBalance = opBalance;
	}

	@Column(name = "underGroup", length = 255)
	public String getUnderGroup() {
		return underGroup;
	}

	public void setUnderGroup(String underGroup) {
		this.underGroup = underGroup;
	}

	@Column(name = "debitCredit", length = 255)
	public String getDebitCredit() {
		return debitCredit;
	}

	public void setDebitCredit(String debitCredit) {
		this.debitCredit = debitCredit;
	}

	@Column(name = "strDirectory", length = 255)
	public String getStrDirectory() {
		return strDirectory;
	}

	public void setStrDirectory(String strDirectory) {
		this.strDirectory = strDirectory;
	}

	@Column(name = "bankChequeReport", length = 255)
	public String getBankChequeReport() {
		return bankChequeReport;
	}

	public void setBankChequeReport(String bankChequeReport) {
		this.bankChequeReport = bankChequeReport;
	}

	@Column(name = "rewardDirectory", length = 255)
	public String getRewardDirectory() {
		return rewardDirectory;
	}

	public void setRewardDirectory(String rewardDirectory) {
		this.rewardDirectory = rewardDirectory;
	}
	
	@Column(name = "textinput", length = 255)
	public String getTextinput() {
		return textinput;
	}

	public void setTextinput(String textinput) {
		this.textinput = textinput;
	}

	@Column(name = "deactivate")
	public Integer getDeactivate() {
		return deactivate;
	}

	public void setDeactivate(Integer deactivate) {
		this.deactivate = deactivate;
	}

	@Column(name = "manifestReportName", length = 255)
	public String getManifestReportName() {
		return manifestReportName;
	}

	public void setManifestReportName(String manifestReportName) {
		this.manifestReportName = manifestReportName;
	}

	@Column(name = "binNo", length = 255)
	public String getBinNo() {
		return binNo;
	}

	public void setBinNo(String binNo) {
		this.binNo = binNo;
	}

	@Column(name = "exporterHouse", length = 255)
	public String getExporterHouse() {
		return exporterHouse;
	}

	public void setExporterHouse(String exporterHouse) {
		this.exporterHouse = exporterHouse;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "certificateDate", nullable = false, length = 19)
	public Date getCertificateDate() {
		return certificateDate;
	}

	public void setCertificateDate(Date certificateDate) {
		this.certificateDate = certificateDate;
	}
	
	@Column(name = "validUptoDate", length = 255)
	public Date getValidUptoDate() {
		return validUptoDate;
	}

	public void setValidUptoDate(Date validUptoDate) {
		this.validUptoDate = validUptoDate;
	}

	@Column(name = "ifsCode", length = 255)
	public String getIfsCode() {
		return ifsCode;
	}

	public void setIfsCode(String ifsCode) {
		this.ifsCode = ifsCode;
	}

	@Column(name = "stExciseReg", length = 255)
	public String getStExciseReg() {
		return stExciseReg;
	}

	public void setStExciseReg(String stExciseReg) {
		this.stExciseReg = stExciseReg;
	}

	@Column(name = "gstNo", length = 255)
	public String getGstNo() {
		return gstNo;
	}

	public void setGstNo(String gstNo) {
		this.gstNo = gstNo;
	}

	@Column(name = "branchSrNo", length = 255)
	public String getBranchSrNo() {
		return branchSrNo;
	}

	public void setBranchSrNo(String branchSrNo) {
		this.branchSrNo = branchSrNo;
	}

	@Column(name = "totalBranch", length = 255)
	public String getTotalBranch() {
		return totalBranch;
	}

	public void setTotalBranch(String totalBranch) {
		this.totalBranch = totalBranch;
	}

	@Column(name = "pinCode", length = 255)
	public String getPinCode() {
		return pinCode;
	}

	public void setPinCode(String pinCode) {
		this.pinCode = pinCode;
	}

	@Column(name = "contactPerson", length = 255)
	public String getContactPerson() {
		return contactPerson;
	}

	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	@Column(name = "phone", length = 255)
	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "mobile", length = 255)
	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "email", length = 255)
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	@Column(name = "commercialTaxRegState", length = 255)
	public String getCommercialTaxRegState() {
		return commercialTaxRegState;
	}

	public void setCommercialTaxRegState(String commercialTaxRegState) {
		this.commercialTaxRegState = commercialTaxRegState;
	}

	@Column(name = "commercialTaxType", length = 255)
	public String getCommercialTaxType() {
		return commercialTaxType;
	}

	public void setCommercialTaxType(String commercialTaxType) {
		this.commercialTaxType = commercialTaxType;
	}

	@Column(name = "commercialTaxRegNo", length = 255)
	public String getCommercialTaxRegNo() {
		return commercialTaxRegNo;
	}

	public void setCommercialTaxRegNo(String commercialTaxRegNo) {
		this.commercialTaxRegNo = commercialTaxRegNo;
	}

	@Column(name = "iecCode", length = 255)
	public String getIecCode() {
		return iecCode;
	}

	public void setIecCode(String iecCode) {
		this.iecCode = iecCode;
	}

	@Column(name = "branchSerialNo", length = 255)
	public String getBranchSerialNo() {
		return branchSerialNo;
	}

	public void setBranchSerialNo(String branchSerialNo) {
		this.branchSerialNo = branchSerialNo;
	}

	@Column(name = "commissionRate", length = 255)
	public String getCommissionRate() {
		return commissionRate;
	}

	public void setCommissionRate(String commissionRate) {
		this.commissionRate = commissionRate;
	}

	@Column(name = "division", length = 255)
	public String getDivision() {
		return division;
	}

	public void setDivision(String division) {
		this.division = division;
	}

	@Column(name = "range", length = 255)
	public String getRange() {
		return range;
	}

	public void setRange(String range) {
		this.range = range;
	}

	@Column(name = "branch", length = 255)
	public String getBranch() {
		return branch;
	}

	public void setBranch(String branch) {
		this.branch = branch;
	}

	@Column(name = "drawBankAccountNo", length = 255)
	public String getDrawBankAccountNo() {
		return drawBankAccountNo;
	}

	public void setDrawBankAccountNo(String drawBankAccountNo) {
		this.drawBankAccountNo = drawBankAccountNo;
	}

	@Column(name = "bankName", length = 255)
	public String getBankName() {
		return bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "drawBankAddress", length = 255)
	public String getDrawBankAddress() {
		return drawBankAddress;
	}

	public void setDrawBankAddress(String drawBankAddress) {
		this.drawBankAddress = drawBankAddress;
	}

	@Column(name = "address", length = 255)
	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}
	
	@Column(name = "iecCodeNo", length = 255)
	public String getIecCodeNo() {
		return iecCodeNo;
	}

	public void setIecCodeNo(String iecCodeNo) {
		this.iecCodeNo = iecCodeNo;
	}

	@Column(name = "organization", length = 255)
	public String getOrganization() {
		return organization;
	}

	public void setOrganization(String organization) {
		this.organization = organization;
	}

	@Column(name = "panNo", length = 255)
	public String getPanNo() {
		return panNo;
	}

	public void setPanNo(String panNo) {
		this.panNo = panNo;
	}

	@Column(name = "accountNo", length = 255)
	public String getAccountNo() {
		return accountNo;
	}

	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}

	@Column(name = "grBankAdCode", length = 255)
	public String getGrBankAdCode() {
		return grBankAdCode;
	}

	public void setGrBankAdCode(String grBankAdCode) {
		this.grBankAdCode = grBankAdCode;
	}

	@Column(name = "grBankName", length = 255)
	public String getGrBankName() {
		return grBankName;
	}

	public void setGrBankName(String grBankName) {
		this.grBankName = grBankName;
	}

	@Column(name = "grBankaddress", length = 255)
	public String getGrBankaddress() {
		return grBankaddress;
	}

	public void setGrBankaddress(String grBankaddress) {
		this.grBankaddress = grBankaddress;
	}

	@Column(name = "grBankTotalBranch", length = 255)
	public String getGrBankTotalBranch() {
		return grBankTotalBranch;
	}

	public void setGrBankTotalBranch(String grBankTotalBranch) {
		this.grBankTotalBranch = grBankTotalBranch;
	}

	@Column(name = "iecCodeThirdParty", length = 255)
	public String getIecCodeThirdParty() {
		return iecCodeThirdParty;
	}

	public void setIecCodeThirdParty(String iecCodeThirdParty) {
		this.iecCodeThirdParty = iecCodeThirdParty;
	}

	@Column(name = "branchSrNoThirdParty", length = 255)
	public String getBranchSrNoThirdParty() {
		return branchSrNoThirdParty;
	}

	public void setBranchSrNoThirdParty(String branchSrNoThirdParty) {
		this.branchSrNoThirdParty = branchSrNoThirdParty;
	}

	@Column(name = "commissionRateThirdParty", length = 255)
	public String getCommissionRateThirdParty() {
		return commissionRateThirdParty;
	}

	public void setCommissionRateThirdParty(String commissionRateThirdParty) {
		this.commissionRateThirdParty = commissionRateThirdParty;
	}

	@Column(name = "divisionThirdParty", length = 255)
	public String getDivisionThirdParty() {
		return divisionThirdParty;
	}

	public void setDivisionThirdParty(String divisionThirdParty) {
		this.divisionThirdParty = divisionThirdParty;
	}

	@Column(name = "rangeThirdParty", length = 255)
	public String getRangeThirdParty() {
		return rangeThirdParty;
	}

	public void setRangeThirdParty(String rangeThirdParty) {
		this.rangeThirdParty = rangeThirdParty;
	}

	@Column(name = "nameAddress", length = 355)
	public String getNameAddress() {
		return nameAddress;
	}

	public void setNameAddress(String nameAddress) {
		this.nameAddress = nameAddress;
	}

	@Column(name = "exporterClass", length = 255)
	public String getExporterClass() {
		return exporterClass;
	}

	public void setExporterClass(String exporterClass) {
		this.exporterClass = exporterClass;
	}

	@Column(name = "grBank", length = 255)
	public String getGrBank() {
		return grBank;
	}

	public void setGrBank(String grBank) {
		this.grBank = grBank;
	}

	public void setPartyId(long partyId) {
		this.partyId = partyId;
	}

	public void setState(State state) {
		this.state = state;
	}

	@Column(name = "certificateNo", length = 255)
	public Date getCertificateNo() {
		return certificateNo;
	}

	public void setCertificateNo(Date certificateNo) {
		this.certificateNo = certificateNo;
	}

	@Column(name = "name", length = 255)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	
	
}
