package com.webapp.project.modules.party.model;
// Generated Jul 9, 2017 1:44:32 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.webapp.project.framework.model.AppUser;
import com.webapp.project.modules.masters.model.City;
import com.webapp.project.modules.masters.model.State;

/**
 * Jobcard generated by hbm2java
 */
@Entity
@Table(name = "partyLicense", catalog = "websystique")
public class PartyLicense implements java.io.Serializable {

	private long partyLicenseId;
	private AppUser appUser;
	private Date licDate;
	private Date regDate;
	private Double qty;
	private String regNo;
	private String createUsertype;
	private Party party; 
	private Date createDate;
	private Date modifyDate;
	private Integer createUserId;
	private String createUsername;
	private String partyLicenseType;
	
	
	public PartyLicense() {
	}

	@Id

	@Column(name = "partyLicenseId", unique = true, nullable = false)
	public long getPartyLicenseId() {
		return this.partyLicenseId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public AppUser getAppUser() {
		return this.appUser;
	}

	public String getRegNo() {
		return regNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "licDate", nullable = false, length = 19)
	public Date getLicDate() {
		return licDate;
	}

	public void setLicDate(Date licDate) {
		this.licDate = licDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "regDate", nullable = false, length = 19)
	public Date getRegDate() {
		return regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@Column(name = "qty")
	public Double getQty() {
		return qty;
	}

	public void setQty(Double qty) {
		this.qty = qty;
	}

	@Column(name = "regNo")
	public void setRegNo(String regNo) {
		this.regNo = regNo;
	}

	@Column(name = "create_usertype", length = 20)
	public String getCreateUsertype() {
		return createUsertype;
	}

	public void setCreateUsertype(String createUsertype) {
		this.createUsertype = createUsertype;
	}

	public void setPartyLicenseId(long partyLicenseId) {
		this.partyLicenseId = partyLicenseId;
	}

	public void setAppUser(AppUser appUser) {
		this.appUser = appUser;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "partyId")
	public Party getParty() {
		return this.party;
	}

	public void setParty(Party party) {
		this.party = party;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DATE", length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFY_DATE", length = 10)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "create_userID")
	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	@Column(name = "create_username", nullable = false, length = 40)
	public String getCreateUsername() {
		return this.createUsername;
	}

	public void setCreateUsername(String createUsername) {
		this.createUsername = createUsername;
	}

	@Column(name = "partyLicenseType")
	public String getPartyLicenseType() {
		return partyLicenseType;
	}

	public void setPartyLicenseType(String partyLicenseType) {
		this.partyLicenseType = partyLicenseType;
	}

}
