package com.webapp.project.modules.party.model;
// Generated Jul 9, 2017 1:44:32 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.webapp.project.framework.model.AppUser;
import com.webapp.project.framework.model.BaseDTO;
import com.webapp.project.modules.masters.model.City;
import com.webapp.project.modules.masters.model.State;

/**
 * Jobcard generated by hbm2java
 */
public class PartyLicenseDTO extends BaseDTO {

	private long partyLicenseId;
	private AppUser appUser;
	private Date licDate;
	private Date regDate;
	private Double qty;
	private String regNo;
	private String createUsertype;
	private Party party; 
	private Date createDate;
	private Date modifyDate;
	private Integer createUserId;
	private String createUsername;
	private Integer selectedPartyLicenseTypeId;
	
	public enum partyLicenseType{
		DEEC(1),
		EPCG(2);
		
		private int licenseTypeId;

		private partyLicenseType(int licenseTypeId) {
			this.licenseTypeId = licenseTypeId;
		}

		public int getLicenseTypeId() {
			return licenseTypeId;
		}

		public void setLicenseTypeId(int licenseTypeId) {
			this.licenseTypeId = licenseTypeId;
		}
		
	}
	
	
	public PartyLicenseDTO() {
	}

	public long getPartyLicenseId() {
		return this.partyLicenseId;
	}

	public AppUser getAppUser() {
		return this.appUser;
	}

	public String getRegNo() {
		return regNo;
	}

	public Date getLicDate() {
		return licDate;
	}

	public void setLicDate(Date licDate) {
		this.licDate = licDate;
	}

	public Date getRegDate() {
		return regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	public Double getQty() {
		return qty;
	}

	public void setQty(Double qty) {
		this.qty = qty;
	}

	public void setRegNo(String regNo) {
		this.regNo = regNo;
	}
	
	public String getCreateUsertype() {
		return createUsertype;
	}

	public void setCreateUsertype(String createUsertype) {
		this.createUsertype = createUsertype;
	}

	public void setPartyLicenseId(long partyLicenseId) {
		this.partyLicenseId = partyLicenseId;
	}

	public void setAppUser(AppUser appUser) {
		this.appUser = appUser;
	}

	public Party getParty() {
		return this.party;
	}

	public void setParty(Party party) {
		this.party = party;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	public String getCreateUsername() {
		return this.createUsername;
	}

	public void setCreateUsername(String createUsername) {
		this.createUsername = createUsername;
	}

	public Integer getSelectedPartyLicenseTypeId() {
		return selectedPartyLicenseTypeId;
	}

	public void setSelectedPartyLicenseTypeId(Integer selectedPartyLicenseTypeId) {
		this.selectedPartyLicenseTypeId = selectedPartyLicenseTypeId;
	}
}
