package com.webapp.project.modules.parent.model;
// Generated Jul 9, 2017 5:31:29 PM by Hibernate Tools 4.3.1.Final


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.webapp.project.framework.model.AppUser;

/**
 * Parent generated by hbm2java
 */
@Entity
@Table(name="parent"
    ,catalog="websystique"
)
public class Parent  implements java.io.Serializable {


     private Long parentId;
     private AppUser appUser;
     private String firstName;
     private String middleName;
     private String lastName;
     private String fatherName;
     private String motherName;
     private String fatherProfession;
     private String motherProfession;
     private String email;
     private String phone;
     private String address;
     private String photo;
     private String username;
     private String password;
     private String usertype;
     private Date createDate;
     private Date modifyDate;
     private Integer createUserId;
     private String createUsername;
     private String createUsertype;
     private int parentactive;

    public Parent() {
    }

	
    public Parent(String lastName, String fatherName, String motherName, String fatherProfession, String motherProfession, Date createDate, Date modifyDate, String createUsername, String createUsertype, int parentactive) {
        this.lastName = lastName;
        this.fatherName = fatherName;
        this.motherName = motherName;
        this.fatherProfession = fatherProfession;
        this.motherProfession = motherProfession;
        this.createDate = createDate;
        this.modifyDate = modifyDate;
        this.createUsername = createUsername;
        this.createUsertype = createUsertype;
        this.parentactive = parentactive;
    }
    public Parent(AppUser appUser, String firstName, String middleName, String lastName, String fatherName, String motherName, String fatherProfession, String motherProfession, String email, String phone, String address, String photo, String username, String password, String usertype, Date createDate, Date modifyDate, Integer createUserId, String createUsername, String createUsertype, int parentactive) {
       this.appUser = appUser;
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.fatherName = fatherName;
       this.motherName = motherName;
       this.fatherProfession = fatherProfession;
       this.motherProfession = motherProfession;
       this.email = email;
       this.phone = phone;
       this.address = address;
       this.photo = photo;
       this.username = username;
       this.password = password;
       this.usertype = usertype;
       this.createDate = createDate;
       this.modifyDate = modifyDate;
       this.createUserId = createUserId;
       this.createUsername = createUsername;
       this.createUsertype = createUsertype;
       this.parentactive = parentactive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="parentID", unique=true, nullable=false)
    public Long getParentId() {
        return this.parentId;
    }
    
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="userId")
    public AppUser getAppUser() {
        return this.appUser;
    }
    
    public void setAppUser(AppUser appUser) {
        this.appUser = appUser;
    }

    
    @Column(name="First_Name", length=60)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="Middle_Name", length=60)
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    
    @Column(name="Last_Name", nullable=false, length=60)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="father_name", nullable=false, length=60)
    public String getFatherName() {
        return this.fatherName;
    }
    
    public void setFatherName(String fatherName) {
        this.fatherName = fatherName;
    }

    
    @Column(name="mother_name", nullable=false, length=60)
    public String getMotherName() {
        return this.motherName;
    }
    
    public void setMotherName(String motherName) {
        this.motherName = motherName;
    }

    
    @Column(name="father_profession", nullable=false, length=40)
    public String getFatherProfession() {
        return this.fatherProfession;
    }
    
    public void setFatherProfession(String fatherProfession) {
        this.fatherProfession = fatherProfession;
    }

    
    @Column(name="mother_profession", nullable=false, length=40)
    public String getMotherProfession() {
        return this.motherProfession;
    }
    
    public void setMotherProfession(String motherProfession) {
        this.motherProfession = motherProfession;
    }

    
    @Column(name="email", length=40)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="phone")
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="address", length=65535)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="photo", length=200)
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    
    @Column(name="username", length=40)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", length=128)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="usertype", length=20)
    public String getUsertype() {
        return this.usertype;
    }
    
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", nullable=false, length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modify_date", nullable=false, length=19)
    public Date getModifyDate() {
        return this.modifyDate;
    }
    
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    
    @Column(name="create_userID")
    public Integer getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="create_username", nullable=false, length=40)
    public String getCreateUsername() {
        return this.createUsername;
    }
    
    public void setCreateUsername(String createUsername) {
        this.createUsername = createUsername;
    }

    
    @Column(name="create_usertype", nullable=false, length=20)
    public String getCreateUsertype() {
        return this.createUsertype;
    }
    
    public void setCreateUsertype(String createUsertype) {
        this.createUsertype = createUsertype;
    }

    
    @Column(name="parentactive", nullable=false)
    public int getParentactive() {
        return this.parentactive;
    }
    
    public void setParentactive(int parentactive) {
        this.parentactive = parentactive;
    }


}


