package com.webapp.project.framework.model;
// Generated Jul 9, 2017 5:31:29 PM by Hibernate Tools 4.3.1.Final


import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserDocument generated by hbm2java
 */
@Entity
@Table(name="user_document"
    ,catalog="websystique"
)
public class UserDocument  implements java.io.Serializable {


     private Long id;
     private AppUser appUser;
     private String name;
     private String description;
     private String type;
     private byte[] content;

    public UserDocument() {
    }

	
    public UserDocument(AppUser appUser, String name, String type, byte[] content) {
        this.appUser = appUser;
        this.name = name;
        this.type = type;
        this.content = content;
    }
    public UserDocument(AppUser appUser, String name, String description, String type, byte[] content) {
       this.appUser = appUser;
       this.name = name;
       this.description = description;
       this.type = type;
       this.content = content;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public AppUser getAppUser() {
        return this.appUser;
    }
    
    public void setAppUser(AppUser appUser) {
        this.appUser = appUser;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="type", nullable=false, length=100)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="content", nullable=false)
    public byte[] getContent() {
        return this.content;
    }
    
    public void setContent(byte[] content) {
        this.content = content;
    }




}


