package com.webapp.project.modules.masters.model;
// Generated Jul 9, 2017 5:31:29 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.webapp.project.framework.model.AppUser;

/**
 * Accountheadmaster generated by hbm2java
 */
@Entity
@Table(name="accountheadmaster"
    ,catalog="websystique"
)
public class AccountHead  implements java.io.Serializable {


     private long accountHeadId;
     private AppUser appUser;
     private String accountHeadName;
     private String accountHeadCode;
     private String description;
     private Integer active;
     private Date createDate;
     private Date modifiedDate;
     private Integer createUserId;
     private String createUsername;
     private String createUsertype;

    public AccountHead() {
    }

	
    public AccountHead(long accountHeadId, Date modifiedDate) {
        this.accountHeadId = accountHeadId;
        this.modifiedDate = modifiedDate;
    }
    public AccountHead(long accountHeadId, AppUser appUser, String accountHeadName, String accountHeadCode, String description, Integer active, Date createDate, Date modifiedDate, Integer createUserId, String createUsername, String createUsertype) {
       this.accountHeadId = accountHeadId;
       this.appUser = appUser;
       this.accountHeadName = accountHeadName;
       this.accountHeadCode = accountHeadCode;
       this.description = description;
       this.active = active;
       this.createDate = createDate;
       this.modifiedDate = modifiedDate;
       this.createUserId = createUserId;
       this.createUsername = createUsername;
       this.createUsertype = createUsertype;
    }
   
     @Id 

    
    @Column(name="accountHeadId", unique=true, nullable=false)
    public long getAccountHeadId() {
        return this.accountHeadId;
    }
    
    public void setAccountHeadId(long accountHeadId) {
        this.accountHeadId = accountHeadId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="userId")
    public AppUser getAppUser() {
        return this.appUser;
    }
    
    public void setAppUser(AppUser appUser) {
        this.appUser = appUser;
    }

    
    @Column(name="accountHeadName", length=100)
    public String getAccountHeadName() {
        return this.accountHeadName;
    }
    
    public void setAccountHeadName(String accountHeadName) {
        this.accountHeadName = accountHeadName;
    }

    
    @Column(name="accountHeadCode", length=65)
    public String getAccountHeadCode() {
        return this.accountHeadCode;
    }
    
    public void setAccountHeadCode(String accountHeadCode) {
        this.accountHeadCode = accountHeadCode;
    }

    
    @Column(name="description", length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="active")
    public Integer getActive() {
        return this.active;
    }
    
    public void setActive(Integer active) {
        this.active = active;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified_date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    
    @Column(name="create_userId")
    public Integer getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="create_username", length=65)
    public String getCreateUsername() {
        return this.createUsername;
    }
    
    public void setCreateUsername(String createUsername) {
        this.createUsername = createUsername;
    }

    
    @Column(name="create_usertype", length=20)
    public String getCreateUsertype() {
        return this.createUsertype;
    }
    
    public void setCreateUsertype(String createUsertype) {
        this.createUsertype = createUsertype;
    }




}


