package com.webapp.project.modules.masters.model;
// Generated Jul 9, 2017 1:44:32 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "book", catalog = "websystique")
public class Book implements java.io.Serializable {

	private Long bookId;
	private String book;
	private String subjectCode;
	private String author;
	private int price;
	private int quantity;
	private int dueQuantity;
	private String rack;

	public Book() {
	}

	public Book(String book, String subjectCode, String author, int price, int quantity, int dueQuantity, String rack) {
		this.book = book;
		this.subjectCode = subjectCode;
		this.author = author;
		this.price = price;
		this.quantity = quantity;
		this.dueQuantity = dueQuantity;
		this.rack = rack;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "bookID", unique = true, nullable = false)
	public Long getBookId() {
		return this.bookId;
	}

	public void setBookId(Long bookId) {
		this.bookId = bookId;
	}

	@Column(name = "book", nullable = false, length = 60)
	public String getBook() {
		return this.book;
	}

	public void setBook(String book) {
		this.book = book;
	}

	@Column(name = "subject_code", nullable = false)
	public String getSubjectCode() {
		return this.subjectCode;
	}

	public void setSubjectCode(String subjectCode) {
		this.subjectCode = subjectCode;
	}

	@Column(name = "author", nullable = false, length = 100)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "price", nullable = false)
	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "due_quantity", nullable = false)
	public int getDueQuantity() {
		return this.dueQuantity;
	}

	public void setDueQuantity(int dueQuantity) {
		this.dueQuantity = dueQuantity;
	}

	@Column(name = "rack", nullable = false)
	public String getRack() {
		return this.rack;
	}

	public void setRack(String rack) {
		this.rack = rack;
	}

}
