package com.webapp.project.modules.masters.model;
// Generated Jul 9, 2017 1:44:32 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "websystique")
public class Category implements java.io.Serializable {

	private Long categoryId;
	private int hostelId;
	private String classType;
	private String hbalance;
	private String note;

	public Category() {
	}

	public Category(int hostelId, String classType, String hbalance) {
		this.hostelId = hostelId;
		this.classType = classType;
		this.hbalance = hbalance;
	}

	public Category(int hostelId, String classType, String hbalance, String note) {
		this.hostelId = hostelId;
		this.classType = classType;
		this.hbalance = hbalance;
		this.note = note;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "categoryID", unique = true, nullable = false)
	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "hostelID", nullable = false)
	public int getHostelId() {
		return this.hostelId;
	}

	public void setHostelId(int hostelId) {
		this.hostelId = hostelId;
	}

	@Column(name = "class_type", nullable = false, length = 60)
	public String getClassType() {
		return this.classType;
	}

	public void setClassType(String classType) {
		this.classType = classType;
	}

	@Column(name = "hbalance", nullable = false, length = 20)
	public String getHbalance() {
		return this.hbalance;
	}

	public void setHbalance(String hbalance) {
		this.hbalance = hbalance;
	}

	@Column(name = "note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
