package com.webapp.project.modules.masters.model;
// Generated Jul 9, 2017 1:44:32 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.webapp.project.framework.model.AppUser;

/**
 * Chamaster generated by hbm2java
 */
@Entity
@Table(name = "chamaster", catalog = "websystique")
public class Cha implements java.io.Serializable {

	private long chaId;
	private AppUser appUser;
	private String chaName;
	private String address;
	private String chaCode;
	private String email;
	private String telephone;
	private String fax;
	private Date createDate;
	private Date modifiedDate;
	private Integer createUserId;
	private String createUsername;
	private String createUsertype;

	public Cha() {
	}

	public Cha(long chaId, Date modifiedDate) {
		this.chaId = chaId;
		this.modifiedDate = modifiedDate;
	}

	public Cha(long chaId, AppUser appUser, String chaName, String address, String chaCode, String email,
			String telephone, String fax, Date createDate, Date modifiedDate, Integer createUserId,
			String createUsername, String createUsertype) {
		this.chaId = chaId;
		this.appUser = appUser;
		this.chaName = chaName;
		this.address = address;
		this.chaCode = chaCode;
		this.email = email;
		this.telephone = telephone;
		this.fax = fax;
		this.createDate = createDate;
		this.modifiedDate = modifiedDate;
		this.createUserId = createUserId;
		this.createUsername = createUsername;
		this.createUsertype = createUsertype;
	}

	@Id

	@Column(name = "chaId", unique = true, nullable = false)
	public long getChaId() {
		return this.chaId;
	}

	public void setChaId(long chaId) {
		this.chaId = chaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public AppUser getAppUser() {
		return this.appUser;
	}

	public void setAppUser(AppUser appUser) {
		this.appUser = appUser;
	}

	@Column(name = "chaName", length = 100)
	public String getChaName() {
		return this.chaName;
	}

	public void setChaName(String chaName) {
		this.chaName = chaName;
	}

	@Column(name = "Address", length = 355)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "chaCode", length = 65)
	public String getChaCode() {
		return this.chaCode;
	}

	public void setChaCode(String chaCode) {
		this.chaCode = chaCode;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "telephone", length = 20)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "fax", length = 20)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date", nullable = false, length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "create_userId")
	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	@Column(name = "create_username", length = 65)
	public String getCreateUsername() {
		return this.createUsername;
	}

	public void setCreateUsername(String createUsername) {
		this.createUsername = createUsername;
	}

	@Column(name = "create_usertype", length = 20)
	public String getCreateUsertype() {
		return this.createUsertype;
	}

	public void setCreateUsertype(String createUsertype) {
		this.createUsertype = createUsertype;
	}

}
