package com.webapp.project.modules.masters.model;
// Generated Jul 9, 2017 1:44:32 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.webapp.project.framework.model.AppUser;

/**
 * Chargemaster generated by hbm2java
 */
@Entity
@Table(name = "chargemaster", catalog = "websystique")
public class Charge implements java.io.Serializable {

	private long chargeId;
	private AppUser appUser;
	private String chargeName;
	private String chargeCode;
	private String chargeGroup;
	private String taxApplicable;
	private Date createDate;
	private Date modifiedDate;
	private Integer createUserId;
	private String createUsername;
	private String createUsertype;
	private Set<LocalFees> localFees = new HashSet<LocalFees>(0);

	public Charge() {
	}

	public Charge(long chargeId, Date modifiedDate) {
		this.chargeId = chargeId;
		this.modifiedDate = modifiedDate;
	}

	public Charge(long chargeId, AppUser appUser, String chargeName, String chargeCode, String chargeGroup,
			String taxApplicable, Date createDate, Date modifiedDate, Integer createUserId, String createUsername,
			String createUsertype, Set<LocalFees> localFees) {
		this.chargeId = chargeId;
		this.appUser = appUser;
		this.chargeName = chargeName;
		this.chargeCode = chargeCode;
		this.chargeGroup = chargeGroup;
		this.taxApplicable = taxApplicable;
		this.createDate = createDate;
		this.modifiedDate = modifiedDate;
		this.createUserId = createUserId;
		this.createUsername = createUsername;
		this.createUsertype = createUsertype;
		this.localFees = localFees;
	}

	@Id

	@Column(name = "chargeId", unique = true, nullable = false)
	public long getChargeId() {
		return this.chargeId;
	}

	public void setChargeId(long chargeId) {
		this.chargeId = chargeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public AppUser getAppUser() {
		return this.appUser;
	}

	public void setAppUser(AppUser appUser) {
		this.appUser = appUser;
	}

	@Column(name = "chargeName", length = 100)
	public String getChargeName() {
		return this.chargeName;
	}

	public void setChargeName(String chargeName) {
		this.chargeName = chargeName;
	}

	@Column(name = "chargeCode", length = 65)
	public String getChargeCode() {
		return this.chargeCode;
	}

	public void setChargeCode(String chargeCode) {
		this.chargeCode = chargeCode;
	}

	@Column(name = "chargeGroup", length = 20)
	public String getChargeGroup() {
		return this.chargeGroup;
	}

	public void setChargeGroup(String chargeGroup) {
		this.chargeGroup = chargeGroup;
	}

	@Column(name = "taxApplicable", length = 20)
	public String getTaxApplicable() {
		return this.taxApplicable;
	}

	public void setTaxApplicable(String taxApplicable) {
		this.taxApplicable = taxApplicable;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date", nullable = false, length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "create_userId")
	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	@Column(name = "create_username", length = 65)
	public String getCreateUsername() {
		return this.createUsername;
	}

	public void setCreateUsername(String createUsername) {
		this.createUsername = createUsername;
	}

	@Column(name = "create_usertype", length = 20)
	public String getCreateUsertype() {
		return this.createUsertype;
	}

	public void setCreateUsertype(String createUsertype) {
		this.createUsertype = createUsertype;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "charge")
	public Set<LocalFees> getLocalFees() {
		return this.localFees;
	}

	public void setLocalFees(Set<LocalFees> localFees) {
		this.localFees = localFees;
	}

}
