package com.webapp.project.modules.masters.model;
// Generated Jul 9, 2017 1:44:32 AM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.webapp.project.framework.model.AppUser;

/**
 * Consignee generated by hbm2java
 */
@Entity
@Table(name = "consignee", catalog = "websystique")
public class Consignee implements java.io.Serializable {

	private Long consigneeId;
	private AppUser appUser;
	private String name;
	private String code;
	private String notifyParty1;
	private String notifyParty2;
	private String buyer;
	private String address;
	private String details;
	private Date createDate;
	private Date modifyDate;
	private Integer createUserId;
	private String createUsername;
	private String createUsertype;
	private int teacheractive;
	private Set<Jobcard> jobcards = new HashSet<Jobcard>(0);

	public Consignee() {
	}

	public Consignee(String name, String createUsername, String createUsertype, int teacheractive) {
		this.name = name;
		this.createUsername = createUsername;
		this.createUsertype = createUsertype;
		this.teacheractive = teacheractive;
	}

	public Consignee(AppUser appUser, String name, String code, String notifyParty1, String notifyParty2, String buyer,
			String address, String details, Date createDate, Date modifyDate, Integer createUserId,
			String createUsername, String createUsertype, int teacheractive, Set<Jobcard> jobcards) {
		this.appUser = appUser;
		this.name = name;
		this.code = code;
		this.notifyParty1 = notifyParty1;
		this.notifyParty2 = notifyParty2;
		this.buyer = buyer;
		this.address = address;
		this.details = details;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.createUserId = createUserId;
		this.createUsername = createUsername;
		this.createUsertype = createUsertype;
		this.teacheractive = teacheractive;
		this.jobcards = jobcards;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "consigneeId", unique = true, nullable = false)
	public Long getConsigneeId() {
		return this.consigneeId;
	}

	public void setConsigneeId(Long consigneeId) {
		this.consigneeId = consigneeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public AppUser getAppUser() {
		return this.appUser;
	}

	public void setAppUser(AppUser appUser) {
		this.appUser = appUser;
	}

	@Column(name = "NAME", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CODE")
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "NOTIFY_PARTY1")
	public String getNotifyParty1() {
		return this.notifyParty1;
	}

	public void setNotifyParty1(String notifyParty1) {
		this.notifyParty1 = notifyParty1;
	}

	@Column(name = "NOTIFY_PARTY2")
	public String getNotifyParty2() {
		return this.notifyParty2;
	}

	public void setNotifyParty2(String notifyParty2) {
		this.notifyParty2 = notifyParty2;
	}

	@Column(name = "BUYER")
	public String getBuyer() {
		return this.buyer;
	}

	public void setBuyer(String buyer) {
		this.buyer = buyer;
	}

	@Column(name = "ADDRESS")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "DETAILS")
	public String getDetails() {
		return this.details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DATE", length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFY_DATE", length = 10)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "create_userID")
	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	@Column(name = "create_username", nullable = false, length = 40)
	public String getCreateUsername() {
		return this.createUsername;
	}

	public void setCreateUsername(String createUsername) {
		this.createUsername = createUsername;
	}

	@Column(name = "create_usertype", nullable = false, length = 20)
	public String getCreateUsertype() {
		return this.createUsertype;
	}

	public void setCreateUsertype(String createUsertype) {
		this.createUsertype = createUsertype;
	}

	@Column(name = "teacheractive", nullable = false)
	public int getTeacheractive() {
		return this.teacheractive;
	}

	public void setTeacheractive(int teacheractive) {
		this.teacheractive = teacheractive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "consignee")
	public Set<Jobcard> getJobcards() {
		return this.jobcards;
	}

	public void setJobcards(Set<Jobcard> jobcards) {
		this.jobcards = jobcards;
	}

}
