package com.webapp.project.modules.masters.model;
// Generated Jul 9, 2017 1:44:32 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.webapp.project.framework.model.AppUser;

/**
 * Containertypemaster generated by hbm2java
 */
@Entity
@Table(name = "containertypemaster", catalog = "websystique")
public class ContainerType implements java.io.Serializable {

	private long containerTypeId;
	private AppUser appUser;
	private String containerTypeCode;
	private String containerTypeName;
	private String containerTypeDescription;
	private Date createDate;
	private Date modifyDate;
	private Integer createUserId;
	private String createUsername;
	private String createUsertype;
	private int teacheractive;
	private Set<Jobcard> jobcards = new HashSet<Jobcard>(0);

	public ContainerType() {
	}

	public ContainerType(long containerTypeId, Date createDate, Date modifyDate, String createUsername,
			String createUsertype, int teacheractive) {
		this.containerTypeId = containerTypeId;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.createUsername = createUsername;
		this.createUsertype = createUsertype;
		this.teacheractive = teacheractive;
	}

	public ContainerType(long containerTypeId, AppUser appUser, String containerTypeCode,
			String containerTypeName, String containerTypeDescription, Date createDate, Date modifyDate,
			Integer createUserId, String createUsername, String createUsertype, int teacheractive,
			Set<Jobcard> jobcards) {
		this.containerTypeId = containerTypeId;
		this.appUser = appUser;
		this.containerTypeCode = containerTypeCode;
		this.containerTypeName = containerTypeName;
		this.containerTypeDescription = containerTypeDescription;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.createUserId = createUserId;
		this.createUsername = createUsername;
		this.createUsertype = createUsertype;
		this.teacheractive = teacheractive;
		this.jobcards = jobcards;
	}

	@Id

	@Column(name = "containerTypeId", unique = true, nullable = false)
	public long getContainerTypeId() {
		return this.containerTypeId;
	}

	public void setContainerTypeId(long containerTypeId) {
		this.containerTypeId = containerTypeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public AppUser getAppUser() {
		return this.appUser;
	}

	public void setAppUser(AppUser appUser) {
		this.appUser = appUser;
	}

	@Column(name = "containerTypeCode", length = 65)
	public String getContainerTypeCode() {
		return this.containerTypeCode;
	}

	public void setContainerTypeCode(String containerTypeCode) {
		this.containerTypeCode = containerTypeCode;
	}

	@Column(name = "containerTypeName", length = 200)
	public String getContainerTypeName() {
		return this.containerTypeName;
	}

	public void setContainerTypeName(String containerTypeName) {
		this.containerTypeName = containerTypeName;
	}

	@Column(name = "containerTypeDescription", length = 200)
	public String getContainerTypeDescription() {
		return this.containerTypeDescription;
	}

	public void setContainerTypeDescription(String containerTypeDescription) {
		this.containerTypeDescription = containerTypeDescription;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_date", nullable = false, length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "create_userID")
	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	@Column(name = "create_username", nullable = false, length = 40)
	public String getCreateUsername() {
		return this.createUsername;
	}

	public void setCreateUsername(String createUsername) {
		this.createUsername = createUsername;
	}

	@Column(name = "create_usertype", nullable = false, length = 20)
	public String getCreateUsertype() {
		return this.createUsertype;
	}

	public void setCreateUsertype(String createUsertype) {
		this.createUsertype = createUsertype;
	}

	@Column(name = "teacheractive", nullable = false)
	public int getTeacheractive() {
		return this.teacheractive;
	}

	public void setTeacheractive(int teacheractive) {
		this.teacheractive = teacheractive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "containerType")
	public Set<Jobcard> getJobcards() {
		return this.jobcards;
	}

	public void setJobcards(Set<Jobcard> jobcards) {
		this.jobcards = jobcards;
	}

}
