package com.webapp.project.modules.masters.model;
// Generated Jul 9, 2017 1:44:32 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.webapp.project.framework.model.AppUser;
import com.webapp.project.modules.jobcard.model.Jobcard;

/**
 * Customermaster generated by hbm2java
 */
@Entity
@Table(name = "customermaster", catalog = "websystique")
public class Customer implements java.io.Serializable {

	private long customerId;
	private AppUser appUser;
	private City city;
	private Country country;
	private String customerName;
	private String customerCode;
	private String address;
	private String contactNumber;
	private String email;
	private String adcodeNo;
	private String iecode;
	private String panno;
	private String bankName;
	private String password;
	private String fax;
	private String defaultCurrency;
	private String iectype;
	private String iecclass;
	private String website;
	private Date createDate;
	private Date modifiedDate;
	private Integer createUserId;
	private String createUsername;
	private String createUsertype;
	private Set<Jobcard> jobcards = new HashSet<Jobcard>(0);

	public Customer() {
	}

	public Customer(long customerId, Date modifiedDate) {
		this.customerId = customerId;
		this.modifiedDate = modifiedDate;
	}

	public Customer(long customerId, AppUser appUser, City city, Country country,
			String customerName, String customerCode, String address, String contactNumber, String email,
			String adcodeNo, String iecode, String panno, String bankName, String password, String fax,
			String defaultCurrency, String iectype, String iecclass, String website, Date createDate, Date modifiedDate,
			Integer createUserId, String createUsername, String createUsertype, Set<Jobcard> jobcards) {
		this.customerId = customerId;
		this.appUser = appUser;
		this.city = city;
		this.country = country;
		this.customerName = customerName;
		this.customerCode = customerCode;
		this.address = address;
		this.contactNumber = contactNumber;
		this.email = email;
		this.adcodeNo = adcodeNo;
		this.iecode = iecode;
		this.panno = panno;
		this.bankName = bankName;
		this.password = password;
		this.fax = fax;
		this.defaultCurrency = defaultCurrency;
		this.iectype = iectype;
		this.iecclass = iecclass;
		this.website = website;
		this.createDate = createDate;
		this.modifiedDate = modifiedDate;
		this.createUserId = createUserId;
		this.createUsername = createUsername;
		this.createUsertype = createUsertype;
		this.jobcards = jobcards;
	}

	@Id

	@Column(name = "customerId", unique = true, nullable = false)
	public long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(long customerId) {
		this.customerId = customerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public AppUser getAppUser() {
		return this.appUser;
	}

	public void setAppUser(AppUser appUser) {
		this.appUser = appUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cityId")
	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "countryId")
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	@Column(name = "customerName", length = 100)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "customerCode", length = 65)
	public String getCustomerCode() {
		return this.customerCode;
	}

	public void setCustomerCode(String customerCode) {
		this.customerCode = customerCode;
	}

	@Column(name = "address", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "contactNumber", length = 20)
	public String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "adcodeNo", length = 100)
	public String getAdcodeNo() {
		return this.adcodeNo;
	}

	public void setAdcodeNo(String adcodeNo) {
		this.adcodeNo = adcodeNo;
	}

	@Column(name = "iecode", length = 100)
	public String getIecode() {
		return this.iecode;
	}

	public void setIecode(String iecode) {
		this.iecode = iecode;
	}

	@Column(name = "PANNo", length = 20)
	public String getPanno() {
		return this.panno;
	}

	public void setPanno(String panno) {
		this.panno = panno;
	}

	@Column(name = "bankName", length = 100)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "password", length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "fax", length = 20)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "defaultCurrency", length = 100)
	public String getDefaultCurrency() {
		return this.defaultCurrency;
	}

	public void setDefaultCurrency(String defaultCurrency) {
		this.defaultCurrency = defaultCurrency;
	}

	@Column(name = "IECtype", length = 100)
	public String getIectype() {
		return this.iectype;
	}

	public void setIectype(String iectype) {
		this.iectype = iectype;
	}

	@Column(name = "IECclass", length = 100)
	public String getIecclass() {
		return this.iecclass;
	}

	public void setIecclass(String iecclass) {
		this.iecclass = iecclass;
	}

	@Column(name = "website", length = 100)
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date", nullable = false, length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "create_userId")
	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	@Column(name = "create_username", length = 65)
	public String getCreateUsername() {
		return this.createUsername;
	}

	public void setCreateUsername(String createUsername) {
		this.createUsername = createUsername;
	}

	@Column(name = "create_usertype", length = 20)
	public String getCreateUsertype() {
		return this.createUsertype;
	}

	public void setCreateUsertype(String createUsertype) {
		this.createUsertype = createUsertype;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Jobcard> getJobcards() {
		return this.jobcards;
	}

	public void setJobcards(Set<Jobcard> jobcards) {
		this.jobcards = jobcards;
	}

}
