package com.webapp.project.modules.masters.model;
// Generated Jul 9, 2017 1:44:32 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.webapp.project.framework.model.AppUser;

/**
 * Depositbankmaster generated by hbm2java
 */
@Entity
@Table(name = "depositbankmaster", catalog = "websystique")
public class DepositBank implements java.io.Serializable {

	private long bankledgerId;
	private AppUser appUser;
	private String bankledgerName;
	private Integer active;
	private Date createDate;
	private Date modifiedDate;
	private Integer createUserId;
	private String createUsername;
	private String createUsertype;

	public DepositBank() {
	}

	public DepositBank(long bankledgerId, String bankledgerName) {
		this.bankledgerId = bankledgerId;
		this.bankledgerName = bankledgerName;
	}

	public DepositBank(long bankledgerId, AppUser appUser, String bankledgerName, Integer active, Date createDate,
			Date modifiedDate, Integer createUserId, String createUsername, String createUsertype) {
		this.bankledgerId = bankledgerId;
		this.appUser = appUser;
		this.bankledgerName = bankledgerName;
		this.active = active;
		this.createDate = createDate;
		this.modifiedDate = modifiedDate;
		this.createUserId = createUserId;
		this.createUsername = createUsername;
		this.createUsertype = createUsertype;
	}

	@Id

	@Column(name = "bankledgerId", unique = true, nullable = false)
	public long getBankledgerId() {
		return this.bankledgerId;
	}

	public void setBankledgerId(long bankledgerId) {
		this.bankledgerId = bankledgerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public AppUser getAppUser() {
		return this.appUser;
	}

	public void setAppUser(AppUser appUser) {
		this.appUser = appUser;
	}

	@Column(name = "bankledgerName", nullable = false, length = 150)
	public String getBankledgerName() {
		return this.bankledgerName;
	}

	public void setBankledgerName(String bankledgerName) {
		this.bankledgerName = bankledgerName;
	}

	@Column(name = "active")
	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date", length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "create_userId")
	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	@Column(name = "create_username", length = 65)
	public String getCreateUsername() {
		return this.createUsername;
	}

	public void setCreateUsername(String createUsername) {
		this.createUsername = createUsername;
	}

	@Column(name = "create_usertype", length = 20)
	public String getCreateUsertype() {
		return this.createUsertype;
	}

	public void setCreateUsertype(String createUsertype) {
		this.createUsertype = createUsertype;
	}

}
