package com.webapp.project.modules.masters.model;
// Generated Jul 9, 2017 1:44:32 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Grade generated by hbm2java
 */
@Entity
@Table(name = "grade", catalog = "websystique")
public class Grade implements java.io.Serializable {

	private Long gradeId;
	private String grade;
	private String point;
	private int gradefrom;
	private int gradeupto;
	private String note;

	public Grade() {
	}

	public Grade(String grade, String point, int gradefrom, int gradeupto) {
		this.grade = grade;
		this.point = point;
		this.gradefrom = gradefrom;
		this.gradeupto = gradeupto;
	}

	public Grade(String grade, String point, int gradefrom, int gradeupto, String note) {
		this.grade = grade;
		this.point = point;
		this.gradefrom = gradefrom;
		this.gradeupto = gradeupto;
		this.note = note;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "gradeID", unique = true, nullable = false)
	public Long getGradeId() {
		return this.gradeId;
	}

	public void setGradeId(Long gradeId) {
		this.gradeId = gradeId;
	}

	@Column(name = "grade", nullable = false, length = 60)
	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	@Column(name = "point", nullable = false, length = 11)
	public String getPoint() {
		return this.point;
	}

	public void setPoint(String point) {
		this.point = point;
	}

	@Column(name = "gradefrom", nullable = false)
	public int getGradefrom() {
		return this.gradefrom;
	}

	public void setGradefrom(int gradefrom) {
		this.gradefrom = gradefrom;
	}

	@Column(name = "gradeupto", nullable = false)
	public int getGradeupto() {
		return this.gradeupto;
	}

	public void setGradeupto(int gradeupto) {
		this.gradeupto = gradeupto;
	}

	@Column(name = "note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
