package com.webapp.project.modules.masters.model;
// Generated Jul 9, 2017 1:44:32 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.webapp.project.framework.model.AppUser;

/**
 * Jobcard generated by hbm2java
 */
@Entity
@Table(name = "jobcard", catalog = "websystique")
public class Jobcard implements java.io.Serializable {

	private long jobId;
	private AppUser appUser;
	private CargoType cargoType;
	private Consignee consignee;
	private ContainerType containerType;
	private Currency currency;
	private Customer customer;
	private Port portmasterByPortDischargeId;
	private Port portmasterByPortLoadingId;
	private String jobCode;
	private String jobDetails;
	private String jobNo;
	private String quantityType;
	private Long quantity;
	private Long invoiceValue;
	private Date createDate;
	private Date modifiedDate;
	private Integer createUserId;
	private String createUsername;
	private String createUsertype;

	private String bookingId;
	private Date bookingDate;
	private String bookingParty;
	private Date expectedShipmentDate;
	private String salesPerson;
	private String broker;
	private String shipper;
	private Port portOfOriginId;
	private String shippingLineBookingNo;
	private String FreightTerms;
	private String FinalPlaceOfDelivery;
	private String containerPickupPoint;
	private String emptyContainerLocation;
	private Date containerPickupDate;
	private String cargoReady;
	private Date DocsCutOffDate;
	private Date ACDCutOffDate;
	private Date etd;	
	private String poNumber;
	private String activityName;
	
	public Jobcard() {
	}

	public Jobcard(long jobId, Date modifiedDate) {
		this.jobId = jobId;
		this.modifiedDate = modifiedDate;
	}

	public Jobcard(long jobId, AppUser appUser, CargoType cargoType, Consignee consignee,
			ContainerType containerType, Currency currency, Customer customer,
			Port portmasterByPortDischargeId, Port portmasterByPortLoadingId, String jobCode,
			String jobDetails, String jobNo, String quantityType, Long quantity, Long invoiceValue, Date createDate,
			Date modifiedDate, Integer createUserId, String createUsername, String createUsertype) {
		this.jobId = jobId;
		this.appUser = appUser;
		this.cargoType = cargoType;
		this.consignee = consignee;
		this.containerType = containerType;
		this.currency = currency;
		this.customer = customer;
		this.portmasterByPortDischargeId = portmasterByPortDischargeId;
		this.portmasterByPortLoadingId = portmasterByPortLoadingId;
		this.jobCode = jobCode;
		this.jobDetails = jobDetails;
		this.jobNo = jobNo;
		this.quantityType = quantityType;
		this.quantity = quantity;
		this.invoiceValue = invoiceValue;
		this.createDate = createDate;
		this.modifiedDate = modifiedDate;
		this.createUserId = createUserId;
		this.createUsername = createUsername;
		this.createUsertype = createUsertype;
	}

	@Id

	@Column(name = "jobId", unique = true, nullable = false)
	public long getJobId() {
		return this.jobId;
	}

	public void setJobId(long jobId) {
		this.jobId = jobId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public AppUser getAppUser() {
		return this.appUser;
	}

	public void setAppUser(AppUser appUser) {
		this.appUser = appUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cargotypeId")
	public CargoType getCargoType() {
		return this.cargoType;
	}

	public void setCargoType(CargoType cargoType) {
		this.cargoType = cargoType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "consigneeId")
	public Consignee getConsignee() {
		return this.consignee;
	}

	public void setConsignee(Consignee consignee) {
		this.consignee = consignee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "containerId")
	public ContainerType getContainerType() {
		return this.containerType;
	}

	public void setContainerType(ContainerType containerType) {
		this.containerType = containerType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "currencyId")
	public Currency getCurrency() {
		return this.currency;
	}

	public void setCurrency(Currency currency) {
		this.currency = currency;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customerId")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "portDischargeId")
	public Port getPortmasterByPortDischargeId() {
		return this.portmasterByPortDischargeId;
	}

	public void setPortmasterByPortDischargeId(Port portmasterByPortDischargeId) {
		this.portmasterByPortDischargeId = portmasterByPortDischargeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "portLoadingId")
	public Port getPortmasterByPortLoadingId() {
		return this.portmasterByPortLoadingId;
	}

	public void setPortmasterByPortLoadingId(Port portmasterByPortLoadingId) {
		this.portmasterByPortLoadingId = portmasterByPortLoadingId;
	}

	@Column(name = "jobCode", length = 65)
	public String getJobCode() {
		return this.jobCode;
	}

	public void setJobCode(String jobCode) {
		this.jobCode = jobCode;
	}

	@Column(name = "jobDetails", length = 100)
	public String getJobDetails() {
		return this.jobDetails;
	}

	public void setJobDetails(String jobDetails) {
		this.jobDetails = jobDetails;
	}

	@Column(name = "jobNo", length = 100)
	public String getJobNo() {
		return this.jobNo;
	}

	public void setJobNo(String jobNo) {
		this.jobNo = jobNo;
	}

	@Column(name = "quantityType", length = 65)
	public String getQuantityType() {
		return this.quantityType;
	}

	public void setQuantityType(String quantityType) {
		this.quantityType = quantityType;
	}

	@Column(name = "quantity", precision = 11, scale = 0)
	public Long getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Long quantity) {
		this.quantity = quantity;
	}

	@Column(name = "invoiceValue", precision = 11, scale = 0)
	public Long getInvoiceValue() {
		return this.invoiceValue;
	}

	public void setInvoiceValue(Long invoiceValue) {
		this.invoiceValue = invoiceValue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date", nullable = false, length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "create_userId")
	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	@Column(name = "create_username", length = 65)
	public String getCreateUsername() {
		return this.createUsername;
	}

	public void setCreateUsername(String createUsername) {
		this.createUsername = createUsername;
	}

	@Column(name = "create_usertype", length = 20)
	public String getCreateUsertype() {
		return this.createUsertype;
	}

	public void setCreateUsertype(String createUsertype) {
		this.createUsertype = createUsertype;
	}

	@Column(name = "bookingId", length = 200)
	public String getBookingId() {
		return bookingId;
	}

	public void setBookingId(String bookingId) {
		this.bookingId = bookingId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bookingDate", length = 19)
	public Date getBookingDate() {
		return bookingDate;
	}

	public void setBookingDate(Date bookingDate) {
		this.bookingDate = bookingDate;
	}

	@Column(name = "bookingParty", length = 200)
	public String getBookingParty() {
		return bookingParty;
	}

	public void setBookingParty(String bookingParty) {
		this.bookingParty = bookingParty;
	}

	@Column(name = "ExpectedShipmentDate", length = 200)
	public Date getExpectedShipmentDate() {
		return expectedShipmentDate;
	}

	public void setExpectedShipmentDate(Date expectedShipmentDate) {
		this.expectedShipmentDate = expectedShipmentDate;
	}

	@Column(name = "salesPerson", length = 200)
	public String getSalesPerson() {
		return salesPerson;
	}

	public void setSalesPerson(String salesPerson) {
		this.salesPerson = salesPerson;
	}

	@Column(name = "broker", length = 200)
	public String getBroker() {
		return broker;
	}

	public void setBroker(String broker) {
		this.broker = broker;
	}

	@Column(name = "shipper", length = 200)
	public String getShipper() {
		return shipper;
	}

	public void setShipper(String shipper) {
		this.shipper = shipper;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PortOfOriginId")
	public Port getPortOfOriginId() {
		return portOfOriginId;
	}

	public void setPortOfOriginId(Port portOfOriginId) {
		this.portOfOriginId = portOfOriginId;
	}

	@Column(name = "ShippingLineBookingNo", length = 200)
	public String getShippingLineBookingNo() {
		return shippingLineBookingNo;
	}

	public void setShippingLineBookingNo(String shippingLineBookingNo) {
		this.shippingLineBookingNo = shippingLineBookingNo;
	}

	@Column(name = "FreightTerms", length = 200)
	public String getFreightTerms() {
		return FreightTerms;
	}

	public void setFreightTerms(String freightTerms) {
		FreightTerms = freightTerms;
	}

	@Column(name = "FinalPlaceOfDelivery", length = 200)
	public String getFinalPlaceOfDelivery() {
		return FinalPlaceOfDelivery;
	}

	public void setFinalPlaceOfDelivery(String finalPlaceOfDelivery) {
		FinalPlaceOfDelivery = finalPlaceOfDelivery;
	}

	@Column(name = "ContainerPickupPoint", length = 200)
	public String getContainerPickupPoint() {
		return containerPickupPoint;
	}

	public void setContainerPickupPoint(String containerPickupPoint) {
		this.containerPickupPoint = containerPickupPoint;
	}
	
	@Column(name = "EmptyContainerLocation", length = 200)
	public String getEmptyContainerLocation() {
		return emptyContainerLocation;
	}

	public void setEmptyContainerLocation(String emptyContainerLocation) {
		this.emptyContainerLocation = emptyContainerLocation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ContainerPickupDate", length = 19)
	public Date getContainerPickupDate() {
		return containerPickupDate;
	}

	public void setContainerPickupDate(Date containerPickupDate) {
		this.containerPickupDate = containerPickupDate;
	}

	@Column(name = "CargoReady", length = 200)
	public String getCargoReady() {
		return cargoReady;
	}

	public void setCargoReady(String cargoReady) {
		this.cargoReady = cargoReady;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DocsCutOffDate", length = 19)
	public Date getDocsCutOffDate() {
		return DocsCutOffDate;
	}

	public void setDocsCutOffDate(Date docsCutOffDate) {
		DocsCutOffDate = docsCutOffDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ACDCutOffDate", length = 19)
	public Date getACDCutOffDate() {
		return ACDCutOffDate;
	}

	public void setACDCutOffDate(Date aCDCutOffDate) {
		ACDCutOffDate = aCDCutOffDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "etd", length = 19)
	public Date getEtd() {
		return etd;
	}

	public void setEtd(Date etd) {
		this.etd = etd;
	}

	@Column(name = "PoNumber", length = 200)
	public String getPoNumber() {
		return poNumber;
	}

	public void setPoNumber(String poNumber) {
		this.poNumber = poNumber;
	}

	@Column(name = "ActivityName", length = 200)
	public String getActivityName() {
		return activityName;
	}

	public void setActivityName(String activityName) {
		this.activityName = activityName;
	}

}
