package com.webapp.project.modules.masters.model;
// Generated Jul 9, 2017 1:44:32 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.webapp.project.framework.model.AppUser;

/**
 * Localfeesdetailsmaster generated by hbm2java
 */
@Entity
@Table(name = "localfeesdetailsmaster", catalog = "websystique")
public class LocalFeeDetails implements java.io.Serializable {

	private long feedetailsId;
	private AppUser appUser;
	private LocalFees localFees;
	private String value;
	private Long cost;
	private Date validFrom;
	private Date createDate;
	private Date modifiedDate;
	private Integer createUserId;
	private String createUsername;
	private String createUsertype;

	public LocalFeeDetails() {
	}

	public LocalFeeDetails(long feedetailsId, LocalFees localFees, Date modifiedDate) {
		this.feedetailsId = feedetailsId;
		this.localFees = localFees;
		this.modifiedDate = modifiedDate;
	}

	public LocalFeeDetails(long feedetailsId, AppUser appUser, LocalFees localFees, String value,
			Long cost, Date validFrom, Date createDate, Date modifiedDate, Integer createUserId, String createUsername,
			String createUsertype) {
		this.feedetailsId = feedetailsId;
		this.appUser = appUser;
		this.localFees = localFees;
		this.value = value;
		this.cost = cost;
		this.validFrom = validFrom;
		this.createDate = createDate;
		this.modifiedDate = modifiedDate;
		this.createUserId = createUserId;
		this.createUsername = createUsername;
		this.createUsertype = createUsertype;
	}

	@Id

	@Column(name = "feedetailsId", unique = true, nullable = false)
	public long getFeedetailsId() {
		return this.feedetailsId;
	}

	public void setFeedetailsId(long feedetailsId) {
		this.feedetailsId = feedetailsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public AppUser getAppUser() {
		return this.appUser;
	}

	public void setAppUser(AppUser appUser) {
		this.appUser = appUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "feeId", nullable = false)
	public LocalFees getLocalFees() {
		return this.localFees;
	}

	public void setLocalFees(LocalFees localFees) {
		this.localFees = localFees;
	}

	@Column(name = "value", length = 200)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "cost", precision = 11, scale = 0)
	public Long getCost() {
		return this.cost;
	}

	public void setCost(Long cost) {
		this.cost = cost;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "validFrom", length = 19)
	public Date getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date", nullable = false, length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "create_userId")
	public Integer getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	@Column(name = "create_username", length = 65)
	public String getCreateUsername() {
		return this.createUsername;
	}

	public void setCreateUsername(String createUsername) {
		this.createUsername = createUsername;
	}

	@Column(name = "create_usertype", length = 20)
	public String getCreateUsertype() {
		return this.createUsertype;
	}

	public void setCreateUsertype(String createUsertype) {
		this.createUsertype = createUsertype;
	}

}
