package com.webapp.project.modules.masters.model;
// Generated Jul 9, 2017 5:31:29 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.webapp.project.framework.model.AppUser;

/**
 * Localfeesmaster generated by hbm2java
 */
@Entity
@Table(name="localfeesmaster"
    ,catalog="websystique"
)
public class LocalFees  implements java.io.Serializable {


     private long feeId;
     private AppUser appUser;
     private Charge charge;
     private Vendor vendor;
     private String feeName;
     private String feeCode;
     private String remarks;
     private String type;
     private Integer consolecharges;
     private String tallyChargesCode;
     private Date createDate;
     private Date modifiedDate;
     private Integer createUserId;
     private String createUsername;
     private String createUsertype;
     private Set<LocalFeeDetails> localFeeDetails = new HashSet<LocalFeeDetails>(0);

    public LocalFees() {
    }

	
    public LocalFees(long feeId, Date modifiedDate) {
        this.feeId = feeId;
        this.modifiedDate = modifiedDate;
    }
    public LocalFees(long feeId, AppUser appUser, Charge chargemaster, Vendor vendormaster, String feeName, String feeCode, String remarks, String type, Integer consolecharges, String tallyChargesCode, Date createDate, Date modifiedDate, Integer createUserId, String createUsername, String createUsertype, Set<LocalFeeDetails> localFeeDetails) {
       this.feeId = feeId;
       this.appUser = appUser;
       this.charge = charge;
       this.vendor = vendor;
       this.feeName = feeName;
       this.feeCode = feeCode;
       this.remarks = remarks;
       this.type = type;
       this.consolecharges = consolecharges;
       this.tallyChargesCode = tallyChargesCode;
       this.createDate = createDate;
       this.modifiedDate = modifiedDate;
       this.createUserId = createUserId;
       this.createUsername = createUsername;
       this.createUsertype = createUsertype;
       this.localFeeDetails = localFeeDetails;
    }
   
     @Id 

    
    @Column(name="feeId", unique=true, nullable=false)
    public long getFeeId() {
        return this.feeId;
    }
    
    public void setFeeId(long feeId) {
        this.feeId = feeId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="userId")
    public AppUser getAppUser() {
        return this.appUser;
    }
    
    public void setAppUser(AppUser appUser) {
        this.appUser = appUser;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="chargesId")
    public Charge getCharge() {
        return this.charge;
    }
    
    public void setCharge(Charge charge) {
        this.charge = charge;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vendorId")
    public Vendor getVendor() {
        return this.vendor;
    }
    
    public void setVendor(Vendor vendor) {
        this.vendor = vendor;
    }

    
    @Column(name="feeName", length=100)
    public String getFeeName() {
        return this.feeName;
    }
    
    public void setFeeName(String feeName) {
        this.feeName = feeName;
    }

    
    @Column(name="feeCode", length=65)
    public String getFeeCode() {
        return this.feeCode;
    }
    
    public void setFeeCode(String feeCode) {
        this.feeCode = feeCode;
    }

    
    @Column(name="remarks", length=200)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    
    @Column(name="type", length=100)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="consolecharges")
    public Integer getConsolecharges() {
        return this.consolecharges;
    }
    
    public void setConsolecharges(Integer consolecharges) {
        this.consolecharges = consolecharges;
    }

    
    @Column(name="tallyChargesCode", length=100)
    public String getTallyChargesCode() {
        return this.tallyChargesCode;
    }
    
    public void setTallyChargesCode(String tallyChargesCode) {
        this.tallyChargesCode = tallyChargesCode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified_date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    
    @Column(name="create_userId")
    public Integer getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    
    @Column(name="create_username", length=65)
    public String getCreateUsername() {
        return this.createUsername;
    }
    
    public void setCreateUsername(String createUsername) {
        this.createUsername = createUsername;
    }

    
    @Column(name="create_usertype", length=20)
    public String getCreateUsertype() {
        return this.createUsertype;
    }
    
    public void setCreateUsertype(String createUsertype) {
        this.createUsertype = createUsertype;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="localFees")
    public Set<LocalFeeDetails> getLocalFeeDetails() {
        return this.localFeeDetails;
    }
    
    public void setLocalFeeDetails(Set<LocalFeeDetails> localFeeDetails) {
        this.localFeeDetails = localFeeDetails;
    }




}


