package com.webapp.project.modules.masters.model;
// Generated Jul 9, 2017 1:44:32 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.webapp.project.modules.jobcard.model.Jobcard;

/**
 * Portmaster generated by hbm2java
 */
@Entity
@Table(name = "port", catalog = "websystique")
public class Port implements java.io.Serializable {

	private long portId;
	private String portCode;
	private String portName;
	private String portDescription;
	private Set<Agent> agents = new HashSet<Agent>(0);
	private Set<Jobcard> jobcardsForPortDischargeId = new HashSet<Jobcard>(0);
	private Set<Jobcard> jobcardsForPortLoadingId = new HashSet<Jobcard>(0);
	private Set<Jobcard> jobcardsForPortOfOriginId = new HashSet<Jobcard>(0);
	
	public Port() {
	}
	
	public Port(long portId,String portName) {
		this.portId = portId;
		this.portName = portName;
	}

	public Port(long portId) {
		this.portId = portId;
	}

	public Port(long portId, String portCode, String portName, String portDescription,
			Set<Agent> agents, Set<Jobcard> jobcardsForPortDischargeId,
			Set<Jobcard> jobcardsForPortLoadingId,Set<Jobcard> jobcardsForPortOfOriginId) {
		this.portId = portId;
		this.portCode = portCode;
		this.portName = portName;
		this.portDescription = portDescription;
		this.agents = agents;
		this.jobcardsForPortDischargeId = jobcardsForPortDischargeId;
		this.jobcardsForPortLoadingId = jobcardsForPortLoadingId;
		this.jobcardsForPortOfOriginId = jobcardsForPortOfOriginId;
	}

	@Id
	@Column(name = "portId", unique = true, nullable = false)
	public long getPortId() {
		return this.portId;
	}

	public void setPortId(long portId) {
		this.portId = portId;
	}

	@Column(name = "portCode", length = 65)
	public String getPortCode() {
		return this.portCode;
	}

	public void setPortCode(String portCode) {
		this.portCode = portCode;
	}

	@Column(name = "portName", length = 200)
	public String getPortName() {
		return this.portName;
	}

	public void setPortName(String portName) {
		this.portName = portName;
	}

	@Column(name = "portDescription", length = 200)
	public String getPortDescription() {
		return this.portDescription;
	}

	public void setPortDescription(String portDescription) {
		this.portDescription = portDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "port")
	public Set<Agent> getAgents() {
		return this.agents;
	}

	public void setAgents(Set<Agent> agents) {
		this.agents = agents;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "portmasterByPortDischargeId")
	public Set<Jobcard> getJobcardsForPortDischargeId() {
		return this.jobcardsForPortDischargeId;
	}

	public void setJobcardsForPortDischargeId(Set<Jobcard> jobcardsForPortDischargeId) {
		this.jobcardsForPortDischargeId = jobcardsForPortDischargeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "portmasterByPortLoadingId")
	public Set<Jobcard> getJobcardsForPortLoadingId() {
		return this.jobcardsForPortLoadingId;
	}

	public void setJobcardsForPortLoadingId(Set<Jobcard> jobcardsForPortLoadingId) {
		this.jobcardsForPortLoadingId = jobcardsForPortLoadingId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "portOfOriginId")
	public Set<Jobcard> getJobcardsForPortOfOriginId() {
		return jobcardsForPortOfOriginId;
	}

	public void setJobcardsForPortOfOriginId(Set<Jobcard> jobcardsForPortOfOriginId) {
		this.jobcardsForPortOfOriginId = jobcardsForPortOfOriginId;
	}
	
	

}
